### ISSUE TITLE
doesn't seem to work for me

### ISSUE THREAD

**Issue by mattsawyer77** [nathanaelkane/vim-command-w#5]
Hello,

I installed bufkill and then vim-command-w with Vundle. I then added

```
macmenu &File.Close key=<nop>
nmap <D-w> :CommandW<CR>
imap <D-w> <Esc>:CommandW<CR>
```

to my .vimrc, saved it, sourced it, and cmd+w still closes the entire app window. I also tried restarting MacVim from scratch, but the shortcut is still the MacVim default. Any suggestions on troubleshooting?

**Comment by nathanaelkane** [comment]
Not sure if it'll work in `.vimrc`, try adding it to your `.gvimrc`.

**Comment by mattsawyer77** [comment]
Thanks for the fast response! That fixed it.
